spring:
  profiles:
    active: dev
  application:
    name: product-service
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0



server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
