spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

server:
  port: 19095